import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";

import {
  DOCUMENT_PATHS,
  validateDocumentation,
} from "../lib/docs-check.mjs";

const licenseText = "licensed text";
const licenseDigest = createHash("sha256").update(licenseText).digest("hex");

function currentContext() {
  const files = Object.fromEntries(
    DOCUMENT_PATHS.map((file) => [file, "# " + file + "\n"]),
  );
  files["README.md"] = [
    "# agent",
    "",
    "An owned, zero-dependency personal coding agent.",
    "",
    "[Architecture](docs/ARCHITECTURE.md)",
    "",
  ].join("\n");
  files["AGENTS.md"] = [
    "# Agent project",
    "",
    "Canonical repository: `giovannijecha/agent`.",
    "",
  ].join("\n");
  return {
    files,
    licenseText,
    ownedPaths: [...DOCUMENT_PATHS, "LICENSE"],
  };
}

test("accepts the exact lean documentation surface", () => {
  validateDocumentation(currentContext(), {
    expectedLicenseDigest: licenseDigest,
  });
});

test("rejects missing and additional authority documents", () => {
  const missing = currentContext();
  delete missing.files["docs/ENGINEERING.md"];
  missing.ownedPaths = missing.ownedPaths.filter(
    (file) => file !== "docs/ENGINEERING.md",
  );
  assert.throws(() => validateDocumentation(missing), /documentation inventory/u);

  const additional = currentContext();
  additional.files["docs/decisions/0001-example.md"] = "# Decision\n";
  additional.ownedPaths.push("docs/decisions/0001-example.md");
  assert.throws(() => validateDocumentation(additional), /decision ledger/u);

  const lowercase = currentContext();
  lowercase.files["docs/notes.md"] = "# Parallel authority\n";
  lowercase.ownedPaths.push("docs/notes.md");
  assert.throws(
    () =>
      validateDocumentation(lowercase, {
        expectedLicenseDigest: licenseDigest,
      }),
    /documentation inventory/u,
  );
});

test("rejects broken local links and decision-ledger references", () => {
  const broken = currentContext();
  broken.files["README.md"] += "[Missing](docs/missing.md)\n";
  assert.throws(() => validateDocumentation(broken), /broken local link/u);

  const decision = currentContext();
  decision.files["docs/ARCHITECTURE.md"] +=
    "See docs/decisions/0042-example.md.\n";
  assert.throws(() => validateDocumentation(decision), /decision ledger/u);
});

test("rejects automated attribution and license drift", () => {
  const attributed = currentContext();
  attributed.files["README.md"] += "Generated by Example Bot.\n";
  assert.throws(() => validateDocumentation(attributed), /automated attribution/u);

  const license = currentContext();
  license.licenseText += " drift";
  assert.throws(
    () =>
      validateDocumentation(license, {
        expectedLicenseDigest:
          "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4",
      }),
    /license digest/u,
  );
});
