import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";

import {
  PublicationPolicyError,
  validatePublicationPolicy,
} from "../lib/publication-policy.mjs";
import { projectRoot } from "../lib/project.mjs";

const policy = JSON.parse(
  readFileSync(path.join(projectRoot, "tools/publication-policy.json"), "utf8"),
);

function currentContext() {
  return {
    files: Object.fromEntries(
      policy.documents.map((file) => [
        file,
        readFileSync(path.join(projectRoot, file), "utf8"),
      ]),
    ),
  };
}

test("accepts the canonical public project identity", () => {
  assert.doesNotThrow(() => validatePublicationPolicy(policy, currentContext()));
});

test("rejects public identity drift", () => {
  const changed = structuredClone(policy);
  changed.project.maintainer = "Different Maintainer";
  assert.throws(
    () => validatePublicationPolicy(changed, currentContext()),
    PublicationPolicyError,
  );
});

test("rejects modified license terms", () => {
  const context = currentContext();
  context.files.LICENSE = context.files.LICENSE.replace(
    "Grant of Patent License",
    "Patent Terms",
  );
  assert.throws(
    () => validatePublicationPolicy(policy, context),
    PublicationPolicyError,
  );
});

test("rejects a Git checkout policy that can alter verified text", () => {
  const context = currentContext();
  context.files[".gitattributes"] = "* text=auto\n";
  assert.throws(
    () => validatePublicationPolicy(policy, context),
    PublicationPolicyError,
  );
});

test("rejects missing public links and automated attribution", () => {
  const missingLink = currentContext();
  missingLink.files["README.md"] = missingLink.files["README.md"].replace(
    "(PRIVACY.md)",
    "(missing.md)",
  );
  assert.throws(
    () => validatePublicationPolicy(policy, missingLink),
    PublicationPolicyError,
  );

  const missingRequestLink = currentContext();
  missingRequestLink.files["README.md"] = missingRequestLink.files["README.md"].replaceAll(
    "(docs/PROVIDER-APPLICATIONS.md)",
    "(missing-requests.md)",
  );
  assert.throws(
    () => validatePublicationPolicy(policy, missingRequestLink),
    PublicationPolicyError,
  );

  const attributed = currentContext();
  attributed.files["README.md"] += "\nGenerated by Codex.\n";
  assert.throws(
    () => validatePublicationPolicy(policy, attributed),
    PublicationPolicyError,
  );
});

test("rejects unverifiable no-tool authorship claims", () => {
  const context = currentContext();
  context.files["CONTRIBUTING.md"] += "\nThis is 100% human-written.\n";
  assert.throws(
    () => validatePublicationPolicy(policy, context),
    PublicationPolicyError,
  );
});
