/** Public provider-neutral tool framework surface for agent. */

export {
  TOOL_ENGINE_LIMITS,
  ToolDescriptor,
  ToolEngine,
  ToolHandlerOutcome,
  ToolRegistry,
  type ToolCancellation,
  type ToolApprovalField,
  type ToolDescriptorError,
  type ToolDescriptorErrorKind,
  type ToolEngineError,
  type ToolEngineCreateError,
  type ToolEngineErrorKind,
  type ToolExecution,
  type ToolHandler,
  type ToolHandlerError,
  type ToolHandlerErrorKind,
  type ToolHandlerOutcomeStatus,
  type ToolPrepareError,
  type ToolPrepareErrorKind,
  type PreparedToolCall,
  type ToolRegistration,
  type ToolRegistryError,
  type ToolRegistryErrorKind,
  type ToolRisk,
} from "./engine.js";
export {
  BooleanSchema,
  IntegerSchema,
  ListSchema,
  LiteralStringSchema,
  ObjectSchema,
  StringSchema,
  TOOL_SCHEMA_LIMITS,
  validateSchema,
  type ObjectSchemaField,
  type ObjectSchemaProjection,
  type SchemaError,
  type SchemaErrorKind,
  type SchemaValidationError,
  type SchemaValidationErrorKind,
  type ToolSchema,
  type StringSchemaOptions,
} from "./schema.js";
export {
  renderStructuredProjection,
  type StructuredProjectionField,
} from "./projection.js";
