/** Public provider-neutral tool framework surface for agent. */

export {
  TOOL_ENGINE_LIMITS,
  ToolDescriptor,
  ToolEffectPlan,
  ToolEngine,
  ToolHandlerOutcome,
  ToolRegistry,
  type ToolCancellation,
  type ToolApprovalField,
  type ToolDescriptorError,
  type ToolDescriptorErrorKind,
  type ToolEffectPlanError,
  type ToolEffectPlanErrorKind,
  type ToolEngineError,
  type ToolEngineCreateError,
  type ToolEngineErrorKind,
  type ToolExecution,
  type ToolHandler,
  type ToolHandlerError,
  type ToolHandlerErrorKind,
  type ToolHandlerOutcomeStatus,
  type ToolPlanner,
  type ToolPrepareError,
  type ToolPrepareErrorKind,
  type PreparedToolCall,
  type PlannedToolCall,
  type ToolRegistration,
  type ToolRegistryError,
  type ToolRegistryErrorKind,
  type ToolRisk,
} from "./engine.js";
export {
  BooleanSchema,
  IntegerSchema,
  ListSchema,
  LiteralStringSchema,
  ObjectSchema,
  StringSchema,
  TOOL_SCHEMA_LIMITS,
  validateSchema,
  type ObjectSchemaField,
  type ObjectSchemaProjection,
  type ListSchemaOptions,
  type SchemaError,
  type SchemaErrorKind,
  type SchemaValidationError,
  type SchemaValidationErrorKind,
  type ToolSchema,
  type StringSchemaOptions,
} from "./schema.js";
export {
  renderStructuredProjection,
  type StructuredProjectionField,
} from "./projection.js";
